# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentinel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sentinel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esentinel.proto\x12\x08sentinel\"\x88\x01\n\x0e\x41nalyzeRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x36\n\x07\x63ontext\x18\x02 \x03(\x0b\x32%.sentinel.AnalyzeRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x84\x01\n\x0f\x41nalyzeResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x16\n\x0everdict_reason\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65tected_threats\x18\x04 \x03(\t\x12\x1a\n\x12\x61nonymized_content\x18\x05 \x01(\t\"\xaf\x01\n\x14\x41nalyzeOutputRequest\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x17\n\x0foriginal_prompt\x18\x02 \x01(\t\x12<\n\x07\x63ontext\x18\x03 \x03(\x0b\x32+.sentinel.AnalyzeOutputRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8a\x01\n\x15\x41nalyzeOutputResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x16\n\x0everdict_reason\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65tected_threats\x18\x04 \x03(\t\x12\x1a\n\x12sanitized_response\x18\x05 \x01(\t\"B\n\x0bStreamChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\"s\n\x0cStreamResult\x12\x17\n\x0fshould_continue\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x13\n\x0bthreat_type\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t2\xe5\x01\n\rSentinelBrain\x12>\n\x07\x41nalyze\x12\x18.sentinel.AnalyzeRequest\x1a\x19.sentinel.AnalyzeResponse\x12P\n\rAnalyzeOutput\x12\x1e.sentinel.AnalyzeOutputRequest\x1a\x1f.sentinel.AnalyzeOutputResponse\x12\x42\n\rAnalyzeStream\x12\x15.sentinel.StreamChunk\x1a\x16.sentinel.StreamResult(\x01\x30\x01\x42\x10Z\x0esentinel/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentinel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016sentinel/proto'
  _globals['_ANALYZEREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_ANALYZEREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEOUTPUTREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_ANALYZEOUTPUTREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUEST']._serialized_start=29
  _globals['_ANALYZEREQUEST']._serialized_end=165
  _globals['_ANALYZEREQUEST_CONTEXTENTRY']._serialized_start=119
  _globals['_ANALYZEREQUEST_CONTEXTENTRY']._serialized_end=165
  _globals['_ANALYZERESPONSE']._serialized_start=168
  _globals['_ANALYZERESPONSE']._serialized_end=300
  _globals['_ANALYZEOUTPUTREQUEST']._serialized_start=303
  _globals['_ANALYZEOUTPUTREQUEST']._serialized_end=478
  _globals['_ANALYZEOUTPUTREQUEST_CONTEXTENTRY']._serialized_start=119
  _globals['_ANALYZEOUTPUTREQUEST_CONTEXTENTRY']._serialized_end=165
  _globals['_ANALYZEOUTPUTRESPONSE']._serialized_start=481
  _globals['_ANALYZEOUTPUTRESPONSE']._serialized_end=619
  _globals['_STREAMCHUNK']._serialized_start=621
  _globals['_STREAMCHUNK']._serialized_end=687
  _globals['_STREAMRESULT']._serialized_start=689
  _globals['_STREAMRESULT']._serialized_end=804
  _globals['_SENTINELBRAIN']._serialized_start=807
  _globals['_SENTINELBRAIN']._serialized_end=1036
# @@protoc_insertion_point(module_scope)
