# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sentinel_pb2 as sentinel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentinel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentinelBrainStub(object):
    """SENTINEL Brain Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/sentinel.SentinelBrain/Analyze',
                request_serializer=sentinel__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=sentinel__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.AnalyzeOutput = channel.unary_unary(
                '/sentinel.SentinelBrain/AnalyzeOutput',
                request_serializer=sentinel__pb2.AnalyzeOutputRequest.SerializeToString,
                response_deserializer=sentinel__pb2.AnalyzeOutputResponse.FromString,
                _registered_method=True)
        self.AnalyzeStream = channel.stream_stream(
                '/sentinel.SentinelBrain/AnalyzeStream',
                request_serializer=sentinel__pb2.StreamChunk.SerializeToString,
                response_deserializer=sentinel__pb2.StreamResult.FromString,
                _registered_method=True)


class SentinelBrainServicer(object):
    """SENTINEL Brain Service
    """

    def Analyze(self, request, context):
        """Ingress: Analyze user prompt before sending to LLM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeOutput(self, request, context):
        """Egress: Analyze LLM response before sending to user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeStream(self, request_iterator, context):
        """Streaming: Analyze tokens in real-time for SSE responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentinelBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=sentinel__pb2.AnalyzeRequest.FromString,
                    response_serializer=sentinel__pb2.AnalyzeResponse.SerializeToString,
            ),
            'AnalyzeOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeOutput,
                    request_deserializer=sentinel__pb2.AnalyzeOutputRequest.FromString,
                    response_serializer=sentinel__pb2.AnalyzeOutputResponse.SerializeToString,
            ),
            'AnalyzeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalyzeStream,
                    request_deserializer=sentinel__pb2.StreamChunk.FromString,
                    response_serializer=sentinel__pb2.StreamResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.SentinelBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.SentinelBrain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentinelBrain(object):
    """SENTINEL Brain Service
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelBrain/Analyze',
            sentinel__pb2.AnalyzeRequest.SerializeToString,
            sentinel__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.SentinelBrain/AnalyzeOutput',
            sentinel__pb2.AnalyzeOutputRequest.SerializeToString,
            sentinel__pb2.AnalyzeOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sentinel.SentinelBrain/AnalyzeStream',
            sentinel__pb2.StreamChunk.SerializeToString,
            sentinel__pb2.StreamResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
