"""
Django settings for safeclaw project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SEC-01: No insecure fallback — fails loud if not configured
_secret_key = os.environ.get("DJANGO_SECRET_KEY", "")
if not _secret_key:
    import warnings

    warnings.warn(
        "DJANGO_SECRET_KEY not set! Using auto-generated key. "
        "DO NOT use this in production.",
        stacklevel=1,
    )
    import secrets as _s

    _secret_key = _s.token_urlsafe(50)
SECRET_KEY = _secret_key

# SEC-02: DEBUG from environment (default: False for safety)
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() in ("true", "1", "yes")

# SEC-04: ALLOWED_HOSTS from environment
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    # SafeClaw
    "billing",
    "router",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # SafeClaw: Shield scan BEFORE token metering
    "router.shield_middleware.ShieldMiddleware",
]

ROOT_URLCONF = "safeclaw.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "safeclaw.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# ARCH-02: PostgreSQL for production, SQLite fallback for local dev

_database_url = os.environ.get("DATABASE_URL", "")

if _database_url:
    # Production: postgresql://user:pass@host:port/dbname
    import re as _re

    _m = _re.match(
        r"postgresql://(?P<user>[^:]+):(?P<pass>[^@]+)@"
        r"(?P<host>[^:]+):(?P<port>\d+)/(?P<name>.+)",
        _database_url,
    )
    if _m:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": _m.group("name"),
                "USER": _m.group("user"),
                "PASSWORD": _m.group("pass"),
                "HOST": _m.group("host"),
                "PORT": _m.group("port"),
                "CONN_MAX_AGE": 600,
                "OPTIONS": {
                    "connect_timeout": 10,
                },
            }
        }
    else:
        raise ValueError(f"Invalid DATABASE_URL format: {_database_url[:30]}...")
else:
    # Local dev fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # SEC-08: Rate limiting for both anonymous and authenticated users
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only in dev
CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000"
).split(",")


# ---------------------------------------------------------------------------
# ЮKassa
# ---------------------------------------------------------------------------

YOOKASSA_SHOP_ID = os.environ.get("YOOKASSA_SHOP_ID", "")
YOOKASSA_SECRET_KEY = os.environ.get("YOOKASSA_SECRET_KEY", "")
YOOKASSA_RETURN_URL = os.environ.get(
    "YOOKASSA_RETURN_URL", "http://localhost:8000/billing/payment/success/"
)


# ---------------------------------------------------------------------------
# Provider Router
# ---------------------------------------------------------------------------

ROUTER_PROVIDERS = {
    "deepseek": {
        "enabled": True,
        "api_key": os.environ.get("DEEPSEEK_API_KEY", ""),
        "base_url": "https://api.deepseek.com/v1",
        "models": ["deepseek-chat", "deepseek-reasoner"],
        "rate_limit": 60,
        "cost_per_1k_input": 14,
        "cost_per_1k_output": 28,
    },
    "gigachat": {
        "enabled": True,
        "api_key": os.environ.get("GIGACHAT_API_KEY", ""),
        "base_url": ("https://gigachat.devices.sberbank.ru" "/api/v1"),
        "models": [
            "GigaChat-2-Lite",
            "GigaChat-2-Pro",
            "GigaChat-2-Max",
        ],
        "rate_limit": 10,
        # Kopecks per 1K tokens (Feb 2026 pricing)
        "cost_per_1k_input": 7,
        "cost_per_1k_output": 7,
    },
    "yandexgpt": {
        "enabled": True,
        "api_key": os.environ.get("YANDEXGPT_API_KEY", ""),
        "folder_id": os.environ.get("YANDEXGPT_FOLDER_ID", ""),
        "base_url": ("https://llm.api.cloud.yandex.net" "/foundationModels/v1"),
        "models": [
            "yandexgpt-lite",
            "yandexgpt",
            "yandexgpt-pro",
        ],
        "rate_limit": 10,
        "cost_per_1k_input": 20,
        "cost_per_1k_output": 40,
    },
    "tpro": {
        "enabled": True,
        "type": "openai_compat",
        "api_key": os.environ.get("TPRO_API_KEY", "none"),
        "base_url": os.environ.get(
            "TPRO_BASE_URL",
            "http://localhost:8001/v1",
        ),
        "models": ["T-Pro-2.0"],
        "rate_limit": 100,
        "cost_per_1k_input": 0,
        "cost_per_1k_output": 0,
    },
    "qwen": {
        "enabled": True,
        "type": "openai_compat",
        "api_key": os.environ.get("QWEN_API_KEY", "none"),
        "base_url": os.environ.get(
            "QWEN_BASE_URL",
            "http://localhost:8002/v1",
        ),
        "models": [
            "Qwen3-Max-Thinking",
            "Qwen3-Coder-Next",
        ],
        "rate_limit": 100,
        "cost_per_1k_input": 0,
        "cost_per_1k_output": 0,
    },
    "llama": {
        "enabled": True,
        "type": "openai_compat",
        "api_key": os.environ.get("LLAMA_API_KEY", "none"),
        "base_url": os.environ.get(
            "LLAMA_BASE_URL",
            "http://localhost:11434/v1",
        ),
        "models": [
            "Llama-4-Maverick",
            "Llama-4-Scout",
        ],
        "rate_limit": 100,
        "cost_per_1k_input": 0,
        "cost_per_1k_output": 0,
    },
}

# ---------------------------------------------------------------------------
# SENTINEL Shield Configuration (ARCH-01)
# ---------------------------------------------------------------------------

SHIELD_URL = os.environ.get("SHIELD_URL", "http://localhost:8085")
SHIELD_TIMEOUT = int(os.environ.get("SHIELD_TIMEOUT", "5"))
# SHIELD_FAIL_OPEN: if True, requests pass when
# Shield is down. Default: False (fail-closed).
SHIELD_FAIL_OPEN = os.environ.get("SHIELD_FAIL_OPEN", "false").lower() in (
    "true",
    "1",
    "yes",
)
