# Generated by Django 5.2.11 on 2026-02-10 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("team", "Team"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("tokens_limit", models.IntegerField(help_text="-1 = unlimited")),
                (
                    "yokassa_payment_method_id",
                    models.CharField(
                        blank=True,
                        help_text="Saved payment method for recurring payments.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription.created", "Subscription Created"),
                            ("subscription.activated", "Subscription Activated"),
                            ("subscription.renewed", "Subscription Renewed"),
                            ("payment.failed", "Payment Failed"),
                            ("subscription.suspended", "Subscription Suspended"),
                            ("subscription.cancelled", "Subscription Cancelled"),
                            ("subscription.upgraded", "Subscription Upgraded"),
                            ("subscription.downgraded", "Subscription Downgraded"),
                            ("payment.refunded", "Payment Refunded"),
                            ("tokens.reset", "Tokens Reset"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "amount_kopecks",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Amount in kopecks (1₽ = 100 kopecks).",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "yokassa_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="ЮKassa payment ID for cross-reference.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Prevents duplicate event processing.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        help_text="Additional event metadata (plan changes, error details, etc).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "billing_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tokens_input",
                    models.PositiveIntegerField(
                        help_text="Number of input tokens consumed."
                    ),
                ),
                (
                    "tokens_output",
                    models.PositiveIntegerField(
                        help_text="Number of output tokens generated."
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="LLM model identifier (e.g. 'gigachat-lite', 'deepseek-v3').",
                        max_length=100,
                    ),
                ),
                (
                    "cost_kopecks",
                    models.PositiveIntegerField(
                        help_text="Our cost for this request in kopecks."
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_logs",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "billing_usage_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of API key. Original shown once at registration.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "billing_users",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email__isnull", False),
                            ("telegram_id__isnull", False),
                            _connector="OR",
                        ),
                        name="user_has_email_or_telegram",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription",
                to="billing.user",
            ),
        ),
    ]
